def generate_report(domain, subdomains, live_hosts, port_data, checklist_done=True, ai_notes=None):
    report = f"# InputCheck Report for {domain}\n\n"

    report += "## Subdomains Found\n"
    for sd in subdomains:
        report += f"- {sd}\n"
    report += "\n"

    report += "## Live Hosts\n"
    for host in live_hosts:
        report += f"- {host}\n"
    report += "\n"

    report += "## Open Ports\n"
    for ip, ports in port_data.items():
        report += f"- {ip}: {', '.join(map(str, ports)) if ports else 'No open ports found'}\n"
    report += "\n"

    report += "## Manual Checklist\n"
    report += f"- Completed: {'Yes' if checklist_done else 'No'}\n\n"

    if ai_notes:
        report += "## AI Vulnerability Insights\n"
        report += ai_notes + "\n\n"

    report += "---\n_Report generated by InputCheck_\n"
    return report
